typography_spectrum: 0.797491
color:
  saturation: 0.9100201798137277
  brandStrength: 0.8978494
  lightness: 0.7274535407777876
  brandColors:
    - '#100E1C'
    - '#EAE8DC'
    - '#554A58'
    - '#8F8A87'
    - '#6F646C'
  rhythmicContrast: 0.8412677522283047
layout_spectrum: 0
author:
  name: Andrew Schnitkey
  email: aschnitkey@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b131ad3c-32b8-4580-8213-12bed66115a0.gif
name: modern saints
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/53b273ed-a637-41a2-8ef4-06b1f4a3977a.jpg
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: '...a life of music, design, and games'
description: established 1979
