collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.797491
color:
  saturation: 0.9100201798137277
  brandStrength: 0.8978494
  lightness: 0.7274535407777876
  brandColors:
    - '#100E1C'
    - '#EAE8DC'
    - '#554A58'
    - '#8F8A87'
    - '#6F646C'
  rhythmicContrast: 0.8412677522283047
layout_spectrum: 0
name: modern saints
